# Generated by Django 5.0.4 on 2024-04-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YourModelName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=36)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=6)),
                ("status", models.CharField(max_length=13)),
                ("consumer_name", models.CharField(max_length=100)),
                ("consumer_address", models.CharField(max_length=200)),
                ("ssn", models.CharField(max_length=11)),
            ],
        ),
    ]
