# Generated by Django 5.0.4 on 2024-04-29 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="YourModelName",
            new_name="Collector",
        ),
    ]
