# Generated by Django 5.0.4 on 2024-04-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0002_rename_yourmodelname_collector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collector",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
