# Generated by Django 5.0.4 on 2024-04-29 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0003_alter_collector_balance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collector",
            old_name="client_id",
            new_name="client_reference_no",
        ),
    ]
